# Generated by Django 2.0.2 on 2018-03-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('element_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('definition', models.CharField(max_length=500, null=True)),
                ('source_system', models.CharField(blank=True, max_length=50, null=True)),
                ('source_detail', models.CharField(blank=True, max_length=50, null=True)),
                ('possible_values', models.CharField(blank=True, max_length=20, null=True)),
                ('data_steward', models.CharField(blank=True, max_length=50, null=True)),
                ('sensitivity', models.CharField(choices=[('TS', 'Top Secret'), ('PR', 'Private'), ('PU', 'Public')], max_length=2)),
                ('conditions', models.CharField(blank=True, max_length=75, null=True)),
                ('stakeholders', models.CharField(blank=True, max_length=50, null=True)),
                ('related_depts', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.CharField(blank=True, max_length=75, null=True)),
                ('refresh_rate', models.CharField(choices=[('B', 'Batch'), ('RT', 'Real Time')], max_length=2)),
                ('timeliness', models.CharField(choices=[('B', 'Batch'), ('RT', 'Real Time')], max_length=2)),
                ('retention', models.DateTimeField()),
                ('other_systems', models.CharField(blank=True, max_length=75, null=True)),
                ('usage', models.CharField(blank=True, max_length=75, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Raci',
            fields=[
                ('raci_name', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('date_enacted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('first_name', models.CharField(blank=True, max_length=75, null=True)),
                ('last_name', models.CharField(blank=True, max_length=75, null=True)),
                ('dg_role', models.CharField(choices=[('O', 'Data Owner'), ('S', 'Data Steward')], max_length=1)),
                ('contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='raci',
            name='users',
            field=models.ManyToManyField(to='glossary.User'),
        ),
        migrations.AddField(
            model_name='domain',
            name='raci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.Raci'),
        ),
        migrations.AddField(
            model_name='domain',
            name='users',
            field=models.ManyToManyField(to='glossary.User'),
        ),
    ]
